// GENERATED by scripts/gen-constants.mjs from public/testnet.json,
// src/data/chains.ts, src/data/venues.ts and src/data/v4Execution.ts.
// Do not edit; re-run the generator and commit the diff.
//
// Arc mainnet (chain id 5042). Despite its filename, public/testnet.json IS
// the served mainnet overlay (`kind: "public"`).

use alloy_primitives::{Address, address};

/// Bloom chain key used for `bloom:chain` reads and the tx outbox.
pub const CHAIN: &str = "arc";
pub const CHAIN_ID: u64 = 5042;
pub const EXPLORER: &str = "https://arc-scan.org";

/// TOLLY public API base (no `/api` prefix).
pub const API_PROD: &str = "https://api.tollylabs.com";

/// USDC ERC-20 view (6 decimals). The same balance is the 18-decimal native gas asset.
pub const USDC: Address = address!("3600000000000000000000000000000000000000");
pub const USDC_ERC20_DECIMALS: u32 = 6;
pub const NATIVE_DECIMALS: u32 = 18;
/// V4 PoolKey currency for native-quote pools (18-decimal native USDC).
pub const V4_NATIVE_CURRENCY: Address = address!("0000000000000000000000000000000000000000");

/// TollyPad: launches and the `tokens(address)` registry ("is it ours").
pub const PAD: Address = address!("cad7ee36ac193bf2eddb7b3e2736c5bdb8269c8b");
/// Furnace: receives the interface fee (through the routers).
pub const FURNACE: Address = address!("e60483df8bb33dbe7c50c47b440e957eb65614c3");
/// TollyMultiRouter (V3 + V2): `swapWithToll` / `swapWithTollV2` / `tollFor`.
pub const MULTI_ROUTER: Address = address!("f28c138a39c234554c847dbef467b073ddbd7451");
/// TollySwapRouter (V3 only). Not used for execution; MULTI_ROUTER is preferred.
pub const TOLLY_SWAP_ROUTER: Address = address!("cebc2e409a85cfa82b086674e6bc5bed51692777");
/// TollyV4Router (follow-up; not executed day-1).
pub const V4_ROUTER: Address = address!("0cf929afcfe846feea4b4487c4d44d4c36abb498");
pub const V4_ROUTER_CODEHASH: &str =
    "0xe2e25994498b0658bef7077606eeadd0b644eb90b855771014ea110c06ae913b";
pub const LOCKER: Address = address!("e20e4297759597da75c8998ee76ec900600ad920");
pub const TOLLY: Address = address!("bc43ce8dec648ea298c4275559b81d6261c90b67");

/// Shared Uniswap V3 infrastructure on Arc (not deployed by TOLLY).
pub const SWAP_ROUTER02: Address = address!("53bf6b0684ec7ef91e1387da3d1a1769bc5a6f77");
pub const V3_FACTORY: Address = address!("f0db7b58379503491d857db50ac9ece64c653918");
pub const POSITION_MANAGER: Address = address!("39654a85a4c05127f5fd6ed22caec077a0fb1377");
pub const QUOTER_V2: Address = address!("7dfd4f31be6814d2906bde155c3e1b146eac1468");

/// Uniswap V4 on Arc (quoting only, day-1).
pub const V4_QUOTER: Address = address!("8dc178efb8111bb0973dd9d722ebeff267c98f94");
pub const UNIVERSAL_ROUTER: Address = address!("4fca4a51ab4f23a7447b3284fbd7d73289a89fb1");
pub const PERMIT2: Address = address!("000000000022d473030f116ddee9f6b43ac78ba3");

/// Interface fee in basis points of the input (buys of external tokens only).
pub const INTERFACE_FEE_BPS: u64 = 20;
/// Every TollyPad pool is immutable at the 1% tier.
pub const POOL_FEE_PAD: u32 = 10_000;
/// TollyPad total supply, 1e27 raw (1B tokens at 18 decimals).
pub const PAD_TOTAL_SUPPLY_RAW: &str = "1000000000000000000000000000";
pub const PAD_TOKEN_DECIMALS: u32 = 18;

/// sha256 of the vendored `chain/arc.testnet.json` (= public/testnet.json at generation time).
pub const SOURCE_DIGEST: &str =
    "sha256:97797b54687aeaa0ae6619a488494eeca6765a878e88a21e8bbeb1e6b944c871";
