#!/usr/bin/env python3
"""Golden ABI vectors for route/src/abi.rs, produced by an INDEPENDENT encoder.

Uses the `eth_abi` package (the reference Python ABI codec) and `eth_utils`
keccak, never the Petal's own Rust encoder, so a bug in abi.rs cannot hide by
agreeing with itself. The createToken case is byte-for-byte the frontend's own
no-broadcast E2E case (scripts/test-launch-calldata.mjs): `'  Moss Coin  '`,
`' moss '`, an ipfs:// CID for sha256 '42'*32, salt 0x11*32, devBuy 5_000_000,
after the trims/uppercasing that `src/data/launchCall.ts#createTokenArgs`
applies. When the repo's viem is available, `encodeFunctionData` over
`padAbi` must produce the same bytes.

Run: python3 scripts/gen-calldata-fixtures.py   (writes route/tests/fixtures/calldata.json)
"""
import base64
import json
import os
import shutil
import subprocess

from eth_abi import encode
from eth_abi import encoding as _abi_encoding
from eth_utils import keccak

# eth-abi 2.x pads an EMPTY `bytes`/`string` with one extra zero word. The ABI
# spec (`enc(len) pad_right(X)`, padding to a multiple of 32 -> zero bytes for
# an empty value), Solidity's encoder, viem and Foundry's `cast` all emit the
# length word alone. Patch the two encoders so the fixtures follow the spec;
# `cast abi-encode "f(string)" ""` is asserted below when cast is installed.
def _spec_encode_bytes(cls, value):
    cls.validate_value(value)
    padded = value + b"\x00" * ((32 - len(value) % 32) % 32)
    return len(value).to_bytes(32, "big") + padded


_abi_encoding.ByteStringEncoder.encode = classmethod(_spec_encode_bytes)
_abi_encoding.TextStringEncoder.encode = classmethod(
    lambda cls, value: _spec_encode_bytes(_abi_encoding.ByteStringEncoder, value.encode("utf8"))
)

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "..", "route", "tests", "fixtures", "calldata.json")

USDC = "0x3600000000000000000000000000000000000000"
PAD = "0xcad7ee36ac193bf2eddb7b3e2736c5bdb8269c8b"
MULTI_ROUTER = "0xf28c138a39c234554c847dbef467b073ddbd7451"
SWAP_ROUTER02 = "0x53bf6b0684ec7ef91e1387da3d1a1769bc5a6f77"
TOKEN = "0x4753c45fb550fecaa143a47968659117e6ffc2ce"  # BARC
WALLET = "0x" + "aa" * 20
FACTORY = "0x" + "fa" * 20
ZERO = "0x" + "00" * 20


def selector(sig: str) -> bytes:
    return keccak(text=sig)[:4]


def call(sig: str, types, values) -> str:
    return "0x" + (selector(sig) + encode(types, values)).hex()


def ipfs_uri_for_sha256(sha256_hex: str) -> str:
    # Mirror of src/data/launchLogo.ts#ipfsUriForSha256: CIDv1 raw + sha2-256
    # multihash, base32 lower, no padding, multibase prefix 'b'.
    raw = bytes([0x01, 0x55, 0x12, 0x20]) + bytes.fromhex(sha256_hex)
    return "ipfs://b" + base64.b32encode(raw).decode().lower().rstrip("=")


image_uri = ipfs_uri_for_sha256("42" * 32)
salt = bytes.fromhex("11" * 32)

fixtures = {
    "note": "generated by scripts/gen-calldata-fixtures.py with eth_abi; independent of route/src/abi.rs",
    "selectors": {
        "createToken(string,string,(string,string,string,string),bytes32,uint256)": selector(
            "createToken(string,string,(string,string,string,string),bytes32,uint256)"
        ).hex(),
        "tokens(address)": selector("tokens(address)").hex(),
        "exactInputSingle((address,address,uint24,address,uint256,uint256,uint160))": selector(
            "exactInputSingle((address,address,uint24,address,uint256,uint256,uint160))"
        ).hex(),
        "swapWithToll(address,address,uint24,uint256,uint256)": selector(
            "swapWithToll(address,address,uint24,uint256,uint256)"
        ).hex(),
        "swapWithTollV2(address,address,address,uint16,uint256,uint256)": selector(
            "swapWithTollV2(address,address,address,uint16,uint256,uint256)"
        ).hex(),
        "tollFor(address,address,uint256)": selector("tollFor(address,address,uint256)").hex(),
        "quoteExactInputSingle((address,address,uint256,uint24,uint160))": selector(
            "quoteExactInputSingle((address,address,uint256,uint24,uint160))"
        ).hex(),
        "quoteExactInputSingle(((address,address,uint24,int24,address),bool,uint128,bytes))": selector(
            "quoteExactInputSingle(((address,address,uint24,int24,address),bool,uint128,bytes))"
        ).hex(),
        "approve(address,uint256)": selector("approve(address,uint256)").hex(),
        "allowance(address,address)": selector("allowance(address,address)").hex(),
        "balanceOf(address)": selector("balanceOf(address)").hex(),
        "decimals()": selector("decimals()").hex(),
        "symbol()": selector("symbol()").hex(),
        "token0()": selector("token0()").hex(),
        "getReserves()": selector("getReserves()").hex(),
        "getPool(address,address,uint24)": selector("getPool(address,address,uint24)").hex(),
    },
    "topics": {
        "TokenCreated(address,address,string,string,address,string,string,string,string)": "0x"
        + keccak(text="TokenCreated(address,address,string,string,address,string,string,string,string)").hex(),
        "Transfer(address,address,uint256)": "0x" + keccak(text="Transfer(address,address,uint256)").hex(),
        "SwappedWithToll(address,address,address,uint256,uint256,uint256,uint8)": "0x"
        + keccak(text="SwappedWithToll(address,address,address,uint256,uint256,uint256,uint8)").hex(),
    },
    "createToken_moss": {
        "inputs": {
            "name": "Moss Coin",
            "symbol": "MOSS",
            "meta": {
                "imageURI": image_uri,
                "website": "https://moss.example",
                "twitter": "x.com/moss",
                "telegram": "t.me/moss",
            },
            "salt": "0x" + salt.hex(),
            "devBuyQuote": "5000000",
        },
        "calldata": call(
            "createToken(string,string,(string,string,string,string),bytes32,uint256)",
            ["string", "string", "(string,string,string,string)", "bytes32", "uint256"],
            ["Moss Coin", "MOSS", (image_uri, "https://moss.example", "x.com/moss", "t.me/moss"), salt, 5_000_000],
        ),
    },
    "createToken_no_socials": {
        "inputs": {
            "name": "Bare",
            "symbol": "BARE",
            "meta": {"imageURI": "ipfs://bafy", "website": "", "twitter": "", "telegram": ""},
            "salt": "0x" + ("22" * 32),
            "devBuyQuote": "0",
        },
        "calldata": call(
            "createToken(string,string,(string,string,string,string),bytes32,uint256)",
            ["string", "string", "(string,string,string,string)", "bytes32", "uint256"],
            ["Bare", "BARE", ("ipfs://bafy", "", "", ""), bytes.fromhex("22" * 32), 0],
        ),
    },
    "exactInputSingle_buy": {
        "inputs": {
            "tokenIn": USDC,
            "tokenOut": TOKEN,
            "fee": 10000,
            "recipient": WALLET,
            "amountIn": "25000000",
            "amountOutMinimum": "1234567890123456789",
            "sqrtPriceLimitX96": "0",
        },
        "calldata": call(
            "exactInputSingle((address,address,uint24,address,uint256,uint256,uint160))",
            ["(address,address,uint24,address,uint256,uint256,uint160)"],
            [(USDC, TOKEN, 10000, WALLET, 25_000_000, 1234567890123456789, 0)],
        ),
    },
    "swapWithToll_buy": {
        "inputs": {
            "tokenIn": USDC,
            "tokenOut": TOKEN,
            "poolFee": 500,
            "amountIn": "25000000",
            "amountOutMinimum": "999999999999999999999",
        },
        "calldata": call(
            "swapWithToll(address,address,uint24,uint256,uint256)",
            ["address", "address", "uint24", "uint256", "uint256"],
            [USDC, TOKEN, 500, 25_000_000, 999999999999999999999],
        ),
    },
    "swapWithTollV2_buy": {
        "inputs": {
            "tokenIn": USDC,
            "tokenOut": TOKEN,
            "factory": FACTORY,
            "feeBps": 30,
            "amountIn": "25000000",
            "amountOutMinimum": "1",
        },
        "calldata": call(
            "swapWithTollV2(address,address,address,uint16,uint256,uint256)",
            ["address", "address", "address", "uint16", "uint256", "uint256"],
            [USDC, TOKEN, FACTORY, 30, 25_000_000, 1],
        ),
    },
    "tollFor": {
        "inputs": {"tokenIn": USDC, "tokenOut": TOKEN, "amountIn": "25000000"},
        "calldata": call("tollFor(address,address,uint256)", ["address", "address", "uint256"], [USDC, TOKEN, 25_000_000]),
    },
    "approve": {
        "inputs": {"spender": MULTI_ROUTER, "amount": "25000000"},
        "calldata": call("approve(address,uint256)", ["address", "uint256"], [MULTI_ROUTER, 25_000_000]),
    },
    "allowance": {
        "inputs": {"owner": WALLET, "spender": MULTI_ROUTER},
        "calldata": call("allowance(address,address)", ["address", "address"], [WALLET, MULTI_ROUTER]),
    },
    "balanceOf": {
        "inputs": {"owner": WALLET},
        "calldata": call("balanceOf(address)", ["address"], [WALLET]),
    },
    "tokens": {
        "inputs": {"token": TOKEN},
        "calldata": call("tokens(address)", ["address"], [TOKEN]),
        # TokenInfo { creator, pool, lpTokenId }: `pool` is word index 1.
        "return_pad_token": "0x" + encode(["address", "address", "uint256"], [WALLET, "0x" + "50" * 20, 77]).hex(),
        "return_pad_token_pool": "0x" + "50" * 20,
        "return_external_token": "0x" + encode(["address", "address", "uint256"], [ZERO, ZERO, 0]).hex(),
    },
    "quoteExactInputSingle_v3": {
        "inputs": {"tokenIn": USDC, "tokenOut": TOKEN, "amountIn": "24950000", "fee": 500, "sqrtPriceLimitX96": "0"},
        "calldata": call(
            "quoteExactInputSingle((address,address,uint256,uint24,uint160))",
            ["(address,address,uint256,uint24,uint160)"],
            [(USDC, TOKEN, 24_950_000, 500, 0)],
        ),
        "return": "0x"
        + encode(["uint256", "uint160", "uint32", "uint256"], [1234567890123456789012, 79228162514264337593543950336, 3, 120000]).hex(),
        "return_amountOut": "1234567890123456789012",
    },
    "quoteExactInputSingle_v4_native_buy": {
        "inputs": {
            "poolKey": {"currency0": ZERO, "currency1": TOKEN, "fee": 2500, "tickSpacing": 25, "hooks": ZERO},
            "zeroForOne": True,
            "exactAmount": "24950000000000000000",
            "hookData": "0x",
        },
        "calldata": call(
            "quoteExactInputSingle(((address,address,uint24,int24,address),bool,uint128,bytes))",
            ["((address,address,uint24,int24,address),bool,uint128,bytes)"],
            [((ZERO, TOKEN, 2500, 25, ZERO), True, 24_950_000_000_000_000_000, b"")],
        ),
        "return": "0x" + encode(["uint256", "uint256"], [987654321098765432109876, 250000]).hex(),
        "return_amountOut": "987654321098765432109876",
    },
    "quoteExactInputSingle_v4_negative_tick": {
        "inputs": {
            "poolKey": {"currency0": ZERO, "currency1": TOKEN, "fee": 3000, "tickSpacing": -60, "hooks": ZERO},
            "zeroForOne": False,
            "exactAmount": "1",
            "hookData": "0x",
        },
        "calldata": call(
            "quoteExactInputSingle(((address,address,uint24,int24,address),bool,uint128,bytes))",
            ["((address,address,uint24,int24,address),bool,uint128,bytes)"],
            [((ZERO, TOKEN, 3000, -60, ZERO), False, 1, b"")],
        ),
    },
    "getPool": {
        "inputs": {"a": TOKEN, "b": USDC, "fee": 10000},
        "calldata": call("getPool(address,address,uint24)", ["address", "address", "uint24"], [TOKEN, USDC, 10000]),
    },
    "getReserves_return": {
        "return": "0x" + encode(["uint112", "uint112", "uint32"], [18187000000, 1234567890000000000000000, 1789000000]).hex(),
        "reserve0": "18187000000",
        "reserve1": "1234567890000000000000000",
    },
    "symbol_return": {
        "return": "0x" + encode(["string"], ["BARC"]).hex(),
        "value": "BARC",
    },
}

# ---- independent cross-check with Foundry's cast (alloy-sol-types) ----
CAST = shutil.which("cast")


def cast_calldata(sig, *args):
    out = subprocess.run([CAST, "calldata", sig, *args], check=True, capture_output=True, text=True).stdout.strip()
    return out.lower()


if CAST:
    empty = subprocess.run([CAST, "abi-encode", "f(string)", ""], check=True, capture_output=True, text=True).stdout.strip().lower()
    assert "0x" + encode(["string"], [""]).hex() == empty, "empty-string encoding must match cast"
    checks = {
        "createToken_moss": (
            "createToken(string,string,(string,string,string,string),bytes32,uint256)",
            ["Moss Coin", "MOSS", f"({image_uri},https://moss.example,x.com/moss,t.me/moss)", "0x" + salt.hex(), "5000000"],
        ),
        "exactInputSingle_buy": (
            "exactInputSingle((address,address,uint24,address,uint256,uint256,uint160))",
            [f"({USDC},{TOKEN},10000,{WALLET},25000000,1234567890123456789,0)"],
        ),
        "swapWithToll_buy": ("swapWithToll(address,address,uint24,uint256,uint256)", [USDC, TOKEN, "500", "25000000", "999999999999999999999"]),
        "swapWithTollV2_buy": ("swapWithTollV2(address,address,address,uint16,uint256,uint256)", [USDC, TOKEN, FACTORY, "30", "25000000", "1"]),
        "tollFor": ("tollFor(address,address,uint256)", [USDC, TOKEN, "25000000"]),
        "approve": ("approve(address,uint256)", [MULTI_ROUTER, "25000000"]),
        "allowance": ("allowance(address,address)", [WALLET, MULTI_ROUTER]),
        "balanceOf": ("balanceOf(address)", [WALLET]),
        "tokens": ("tokens(address)", [TOKEN]),
        "quoteExactInputSingle_v3": (
            "quoteExactInputSingle((address,address,uint256,uint24,uint160))",
            [f"({USDC},{TOKEN},24950000,500,0)"],
        ),
        "quoteExactInputSingle_v4_native_buy": (
            "quoteExactInputSingle(((address,address,uint24,int24,address),bool,uint128,bytes))",
            [f"(({ZERO},{TOKEN},2500,25,{ZERO}),true,24950000000000000000,0x)"],
        ),
        "quoteExactInputSingle_v4_negative_tick": (
            "quoteExactInputSingle(((address,address,uint24,int24,address),bool,uint128,bytes))",
            [f"(({ZERO},{TOKEN},3000,-60,{ZERO}),false,1,0x)"],
        ),
        "getPool": ("getPool(address,address,uint24)", [TOKEN, USDC, "10000"]),
    }
    for name, (sig, args) in checks.items():
        expected = cast_calldata(sig, *args)
        assert fixtures[name]["calldata"] == expected, f"{name}: eth_abi and cast disagree"
    fixtures["cross_checked_with"] = "foundry cast " + subprocess.run([CAST, "--version"], capture_output=True, text=True).stdout.split()[1]
    print(f"cross-checked {len(checks)} calldata vectors with cast")
else:
    print("cast not installed; skipping the independent cross-check")

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as fh:
    json.dump(fixtures, fh, indent=2)
    fh.write("\n")
print(f"wrote {os.path.relpath(OUT, os.path.join(HERE, '..'))}")
